# Define the goal
geometry_msgs/PoseStamped grasp_pose 
float32 grasp_height 
float32 safety_distance
float32 approach_vector_x
float32 approach_vector_y
float32 approach_vector_z
---
# Define the result
bool success
---
# Define a feedback message
float32 percent_complete