safety_distance: 0.08

speech_output: 'german' # can be english, german or none

rgb_topic: /hsrb/head_rgbd_sensor/rgb/image_rect_color
depth_topic: /hsrb/head_rgbd_sensor/depth_registered/image_rect_raw # 16UC1 with depth in mm
cam_info_topic: /hsrb/head_rgbd_sensor/depth_registered/camera_info
point_cloud_topic: '/hsrb/head_rgbd_sensor/depth_registered/rectified_points'
global_frame: '/map'

grasping_pipeline:

  object_detector_topic: /object_detector/yolov5                      # object detector for known OR unknown objects
                                                                      # decides whether a pose estimator or a grasp point 
                                                                      # estimator is used afterwards
  pose_estimator_topic: /pose_estimator/gdrnet                        # pose estimator for known objects
  grasppoint_estimator_topic: /pose_estimator/find_grasppose_haf      # grasppoint estimator for unknown objects
  
  result_visualization_service_name: '/pose_estimator/result_visualization_service'
  result_visualization_topic: /pose_estimator/result_visualization
  timeout_duration: 40.0
  placement:
    max_attempts: 25