object_mapping:
  ycb_ichores:
    obj_000001: "001_chips_can"
    obj_000002: "002_master_chef_can"
    obj_000003: "003_cracker_box"
    obj_000004: "004_sugar_box"
    obj_000005: "005_tomato_soup_can"
    obj_000006: "006_mustard_bottle"
    obj_000007: "008_pudding_box"
    obj_000008: "009_gelatin_box"
    obj_000009: "010_potted_meat_can"
    obj_000010: "011_banana"
    obj_000011: "013_apple"
    obj_000012: "014_lemon"
    obj_000013: "015_peach"
    obj_000014: "016_pear"
    obj_000015: "017_orange"
    obj_000016: "018_plum"
    obj_000017: "021_bleach_cleanser"
    obj_000018: "024_bowl"
    obj_000019: "025_mug"
    obj_000020: "029_plate"

  hope:
    obj_000001: "alphabet_soup"
    obj_000002: "barbeque_sauce"
    obj_000003: "butter"
    obj_000004: "pitted_cherries"
    obj_000005: "cholocalate_pudding"
    obj_000006: "cookies"
    obj_000007: "corn"
    obj_000008: "cream_cheese"
    obj_000009: "granola_bars"
    obj_000010: "green_beans"
    obj_000011: "tomato_ketchup"
    obj_000012: "macaroni_and_cheese"
    obj_000013: "mayonnaise"
    obj_000014: "milk"
    obj_000015: "sliced_mushrooms"
    obj_000016: "yellow_mustard"
    obj_000017: "orange_juice"
    obj_000018: "parmesan_cheese"
    obj_000019: "peach_slices"
    obj_000020: "peas_and_carrots"
    obj_000021: "pineapple_slices"
    obj_000022: "popcorn"
    obj_000023: "raisins"
    obj_000024: "ranch_dressing"
    obj_000025: "spaghetti"
    obj_000026: "tomato_sauce"
    obj_000027: "fish_tuna"
    obj_000028: "strawberry_yogurt"


